// 人脉-好友
export const LOAD_SOCIAL_FRIEND_DATA = "LOAD_SOCIAL_FRIEND_DATA";
export const CLEAR_SOCIAL_FRIEND_DATA = "CLEAR_SOCIAL_FRIEND_DATA";

// 人脉-通讯录
export const LOAD_SOCIAL_BOOK_DATA = "LOAD_SOCIAL_BOOK_DATA";
export const CLEAR_SOCIAL_BOOK_DATA = "CLEAR_SOCIAL_BOOK_DATA";

// 人脉-五同推荐
export const LOAD_SOCIAL_EXPLORE_DATA = "LOAD_SOCIAL_EXPLORE_DATA";
export const CLEAR_SOCIAL_EXPLORE_DATA = "CLEAR_SOCIAL_EXPLORE_DATA";

// 人脉-主题推荐
export const LOAD_SOCIAL_EXPLORE_TOPIC_DATA = "LOAD_SOCIAL_EXPLORE_TOPIC_DATA";
export const CLEAR_SOCIAL_EXPLORE_TOPIC_DATA = "CLEAR_SOCIAL_EXPLORE_TOPIC_DATA";

// 人脉-主题发现
export const LOAD_SOCIAL_EXPLORE_DISCOVER_DATA = "LOAD_SOCIAL_EXPLORE_DISCOVER_DATA";
export const CLEAR_SOCIAL_EXPLORE_DISCOVER_DATA = "CLEAR_SOCIAL_EXPLORE_DISCOVER_DATA";

// 人脉-附近的人
export const LOAD_SOCIAL_EXPLORE_LOCATION_DATA = "LOAD_SOCIAL_EXPLORE_LOCATION_DATA";
export const CLEAR_SOCIAL_EXPLORE_LOCATION_DATA = "CLEAR_SOCIAL_EXPLORE_LOCATION_DATA";
