export const LOAD_INFOR_INDEX_DATA = "LOAD_INFOR_INDEX_DATA";
export const CLEAR_INFOR_INDEX_DATA = "CLEAR_INFOR_INDEX_DATA";

export const LOAD_INFOR_CHAT_DATA = "LOAD_INFOR_CHAT_DATA";
export const CLEAR_INFOR_CHAT_DATA = "CLEAR_INFOR_CHAT_DATA";

export const LOAD_INFOR_DETAIL_DATA = "LOAD_INFOR_DETAIL_DATA";
export const POST_INFOR_SEND = "POST_INFOR_SEND";
