// 动态-好友
export const LOAD_TREND_FRIEND_DATA = "LOAD_TREND_FRIEND_DATA";
export const CLEAR_TREND_FRIEND_DATA = "CLEAR_TREND_FRIEND_DATA";

// 动态-关注
export const LOAD_TREND_FOLLOW_DATA = "LOAD_TREND_FOLLOW_DATA";
export const CLEAR_TREND_FOLLOW_DATA = "CLEAR_TREND_FOLLOW_DATA";

// 动态-职言
export const LOAD_TREND_WORK_DATA = "LOAD_TREND_WORK_DATA";
export const CLEAR_TREND_WORK_DATA = "CLEAR_TREND_WORK_DATA";

// 动态-操作
export const LOAD_TREND_DETAIL = "LOAD_TREND_DETAIL";
export const POST_TREND_SEND = "POST_TREND_SEND";
export const POST_TREND_PRAISE = "POST_TREND_PRAISE";
export const POST_TREND_COMMENT = "POST_TREND_COMMENT";
export const POST_TREND_SHARE = "POST_TREND_SHARE";

// 行业头条
export const LOAD_TREND_TOUTIAO_DATA = "LOAD_TREND_TOUTIAO_DATA";
export const CLEAR_TREND_TOUTIAO_DATA = "CLEAR_TREND_TOUTIAO_DATA";

// 精选主题
export const LOAD_TREND_TOPIC_DATA = "LOAD_TREND_TOPIC_DATA";
export const CLEAR_TREND_TOPIC_DATA = "CLEAR_TREND_TOPIC_DATA";
